"""URL-slug overrides for Docusaurus-rendered Aztec docs.

Docusaurus uses the ``id:`` field in a Markdown file's YAML frontmatter
as the URL slug, falling back to the filename when ``id:`` is absent.
The corpus path keeps the original filename (e.g.
``registering-sequencer.md``), so a purely path-based URL rewriter
emits ``.../registering-sequencer`` which 404s — the live site serves
the page at ``.../registering_sequencer`` because the file declares
``id: registering_sequencer``.

This module is the authoritative map of those overrides, UNIONED over every
``version-vX.Y.Z/`` corpus the KB serves (two-version KB: v4.3.1 mainnet +
v5.0.0-rc.1 testnet). Keys are version-prefixed corpus-relative source paths
*without* the ``.md`` / ``.mdx`` extension, so the two versions' overrides are
namespaced and never collide. Values are the URL slug Docusaurus serves.

Index files (``foo/index.md``) are NOT listed here even when they
declare an ``id:`` — Docusaurus serves them at the parent path
regardless of the id, and the existing ``_strip_index_suffix`` logic
in ``base.py`` already handles that correctly.

To regenerate after a corpus bump: ``python3 scripts/build_aztec_doc_slug_map.py
--aztec-pkg /path/to/aztec-packages-next-snapshot > application/api/answer/routes/aztec_doc_slugs.py``
(auto-discovers every ``version-v*`` folder in the checkout).
"""

from __future__ import annotations

# Generated by scripts/build_aztec_doc_slug_map.py — UNION over every
# version-v* folder in the next snapshot (network_ + developer_versioned_docs),
# PLUS retained-legacy keys for a still-served version absent from the checkout
# (v4.3.0, until the cutover retires it). Only non-index files where ``id:``
# differs from the filename basename.
AZTEC_DOC_SLUG_OVERRIDES: dict[str, str] = {
    "version-v4.3.0/operators/keystore/creating-keystores": "creating_keystores",
    "version-v4.3.0/operators/reference/ethereum-rpc-reference": "ethereum_rpc_reference",
    "version-v4.3.0/operators/reference/node-api-reference": "node_api_reference",
    "version-v4.3.0/operators/sequencer-management/governance-participation": "creating_and_voting_on_proposals",
    "version-v4.3.0/operators/sequencer-management/slashing-configuration": "slashing_and_offenses",
    "version-v4.3.0/operators/setup/bootnode-operation": "bootnode_operation",
    "version-v4.3.0/operators/setup/building-from-source": "building_from_source",
    "version-v4.3.0/operators/setup/high-availability": "high_availability_sequencers",
    "version-v4.3.0/operators/setup/registering-sequencer": "registering_sequencer",
    "version-v4.3.0/operators/setup/running-a-node": "running_a_node",
    "version-v4.3.0/operators/setup/running-a-prover": "running_a_prover",
    "version-v4.3.0/operators/setup/sequencer-setup": "sequencer_management",
    "version-v4.3.0/operators/setup/staking-provider": "become_a_staking_provider",
    "version-v4.3.0/operators/setup/syncing-best-practices": "syncing_best_practices",
    "version-v4.3.1/operators/keystore/creating-keystores": "creating_keystores",
    "version-v4.3.1/operators/reference/ethereum-rpc-reference": "ethereum_rpc_reference",
    "version-v4.3.1/operators/reference/node-api-reference": "node_api_reference",
    "version-v4.3.1/operators/sequencer-management/governance-participation": "creating_and_voting_on_proposals",
    "version-v4.3.1/operators/sequencer-management/slashing-configuration": "slashing_and_offenses",
    "version-v4.3.1/operators/setup/bootnode-operation": "bootnode_operation",
    "version-v4.3.1/operators/setup/building-from-source": "building_from_source",
    "version-v4.3.1/operators/setup/high-availability": "high_availability_sequencers",
    "version-v4.3.1/operators/setup/registering-sequencer": "registering_sequencer",
    "version-v4.3.1/operators/setup/running-a-node": "running_a_node",
    "version-v4.3.1/operators/setup/running-a-prover": "running_a_prover",
    "version-v4.3.1/operators/setup/sequencer-setup": "sequencer_management",
    "version-v4.3.1/operators/setup/staking-provider": "become_a_staking_provider",
    "version-v4.3.1/operators/setup/syncing-best-practices": "syncing_best_practices",
    "version-v5.0.0-rc.1/operators/keystore/creating-keystores": "creating_keystores",
    "version-v5.0.0-rc.1/operators/reference/ethereum-rpc-reference": "ethereum_rpc_reference",
    "version-v5.0.0-rc.1/operators/reference/node-api-reference": "node_api_reference",
    "version-v5.0.0-rc.1/operators/sequencer-management/governance-participation": "creating_and_voting_on_proposals",
    "version-v5.0.0-rc.1/operators/sequencer-management/slashing-configuration": "slashing_and_offenses",
    "version-v5.0.0-rc.1/operators/setup/bootnode-operation": "bootnode_operation",
    "version-v5.0.0-rc.1/operators/setup/building-from-source": "building_from_source",
    "version-v5.0.0-rc.1/operators/setup/high-availability": "high_availability_sequencers",
    "version-v5.0.0-rc.1/operators/setup/registering-sequencer": "registering_sequencer",
    "version-v5.0.0-rc.1/operators/setup/running-a-node": "running_a_node",
    "version-v5.0.0-rc.1/operators/setup/running-a-prover": "running_a_prover",
    "version-v5.0.0-rc.1/operators/setup/sequencer-setup": "sequencer_management",
    "version-v5.0.0-rc.1/operators/setup/staking-provider": "become_a_staking_provider",
    "version-v5.0.0-rc.1/operators/setup/syncing-best-practices": "syncing_best_practices",
}


def apply_slug_override(rest: str, source_path_no_ext: str) -> str:
    """If ``source_path_no_ext`` has a slug override, replace the last
    segment of ``rest`` with it; otherwise return ``rest`` unchanged.

    ``rest`` is the portion of the URL path after the corpus-prefix
    has been stripped (e.g. ``operators/setup/registering-sequencer``
    when emitting under ``/operate/``). ``source_path_no_ext`` is the
    full corpus-relative path with the extension stripped (e.g.
    ``version-vX.Y.Z/operators/setup/registering-sequencer``) — that
    is the key into ``AZTEC_DOC_SLUG_OVERRIDES``.

    Defensive: index files are served at the parent path regardless of
    their declared ``id:`` (and ``base.py`` strips the ``/index``
    suffix before calling this helper). If a future regen accidentally
    emits a key ending in ``/index``, returning ``rest`` unchanged
    avoids mangling the parent-folder URL.
    """
    if source_path_no_ext.endswith("/index"):
        return rest
    override = AZTEC_DOC_SLUG_OVERRIDES.get(source_path_no_ext)
    if override is None:
        return rest
    parent, sep, _basename = rest.rpartition("/")
    return f"{parent}{sep}{override}" if sep else override
