version: "3"
services:
  honk-ai:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./db:/app/db
      - ./snapshots:/app/snapshots
    restart: unless-stopped
    networks:
      - honk-ai_net

networks:
  honk-ai_net:
    external: true
